server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  mustache:
    expose-session-attributes: true
  datasource: 
      url: jdbc:mariadb://localhost:3306/jusodb
      driver-class-name: org.mariadb.jdbc.Driver
      username: juso
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 

  output:
    ansi:
      enabled: always   

  security:
    user:
      name: test
      password: 1234 